
[package]
name = "fml-docs-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.0"
regex = "1.5.4"
lazy_static = "1.4.0"
handlebars = "4.1.6"
serde_json = "1.0.74"
serde = { version = "1.0.133", features = ["derive"] }