[package]
name = "fml-extension-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
serde_jsonrc = "0.1.0"
notify = "4.0.17"
chrono = "0.4.19"
glob = "0.3.0"
